### ISSUE TITLE
[Question] API Is very confusing

### ISSUE THREAD

**Issue by phmngocnghia** [neutrinojs/webpack-chain#103]
Is i have to learn webpack before use this ? I don't know what i should start with chain.
When to add, when to test, when to use, when to loader ?

Document should provide simple tutorial like webpack to make beginer approch easier

**Comment by endiliey** [comment]
I think you should learn about webpack first. Webpack-chain are more for non beginner & is like a wrapper to native webpack API so user can build config with chain API

**Comment by edmorley** [comment]
Perhaps it would be good to add some of the following to the README?
* cross-references between the webpack-chain concepts and the webpack docs
* more examples
* links to projects that show how they use webpack-chain
