### ISSUE TITLE
Add clearer documentation for rule.exclude

### ISSUE THREAD

**Issue by eliperelman** [neutrinojs/webpack-chain#106]
In neutrinojs/neutrino#1150 there was confusion about the API of rule.exclude.

We should probably add clearer documentation about it to the README here :-)

_(Edited by @edmorley to make it clearer that this is a documentation issue not a bug)_

**Comment by edmorley** [comment]
Hi @homeant, this issue is about adding documentation for the `rule.exclude` feature, whereas that seems unrelated? Generally it's best to keep issues to just one topic. It sounds like you're after `toString()` - see:
https://github.com/neutrinojs/webpack-chain#inspecting-generated-configuration
