### ISSUE TITLE
Hard to manage order of ChainedMap

### ISSUE THREAD

**Issue by Airkro** [neutrinojs/webpack-chain#113]
`webpack-chain` is awesome.

However, it's hard to manage the order of `ChainedMap`, and order is matter in `webpack`, e.g., entry/plugins/module.rules.

Is it possible to provide `.before()` `.after()` API for every `ChainedMap`, same as `config.plugins`.

I suggest to provide the following API:

```js
// same as config.plugin(name).after(otherName)
.before()
.after()

// or maybe
.append()
.prepend()

// sometime will be better then .get(key)
.first()
.last()
.key()

// then we can do this:
const key = config.entryPoints.first().key();
config.entry('abc').before(key).add('abc.js')
```

**Comment by edmorley** [comment]
Hi! Thank you for the suggestion - I can see how that would be useful.

@eliperelman, thoughts?
