### ISSUE TITLE
Remove all CLI only options

### ISSUE THREAD

**Issue by ghost** [neutrinojs/webpack-chain#120]
Option `devServer.color` is CLI only and produces *webpack-dev-server* cryptic error

> options should NOT have additional properties

![webpack-dev-server error](https://user-images.githubusercontent.com/7850073/45427237-05543b00-b6a7-11e8-9479-e799238207ff.png)

see: https://webpack.js.org/configuration/dev-server/#devserver-color-cli-only

Why keep invalid CLI-only options in options anyway?

**Comment by edmorley** [comment]
Hi! I agree those options should not be in there.
Would you be up for opening a PR to remove them? :-)

**Comment by edmorley** [comment]
Closing for the reasons mentioned here:
https://github.com/neutrinojs/webpack-chain/pull/127#issuecomment-507365827

Sorry for the indecision!
