### ISSUE TITLE
Better error message for passing object as plugin arguments

### ISSUE THREAD

**Issue by ghost** [neutrinojs/webpack-chain#121]
Plugin `args` in `config.plugin('plugin', args)` must always be an array, otherwise cryptic error

> cannot call undefined as a function

is produced in `init` method here https://github.com/neutrinojs/webpack-chain/blob/master/src/Plugin.js#L14

Consider add argument validation `isArray` for plugins `args`.

**Comment by edmorley** [comment]
Hi! I agree that would be useful. Would you be able to open a PR? :-)
