### ISSUE TITLE
Cloning a rule

### ISSUE THREAD

**Issue by timkelty** [neutrinojs/webpack-chain#129]
Seems like I should be able to figure this out but am striking out…
I want to leave an existing rule in place, but "clone" it and add it as a new rule (including direct props like `test`, `resourceQuery`, as well as nested maps like `uses`).

```
  const baseRule = neutrino.config.module.rules.get('baseRule');

  neutrino.config.module
    .rule('newRule')
    // I want to apply everything from baseRule (e.g. resourceQuery, use/loaders, etc.)?

    // and then manipulate it
    .test(/newTest/);
```

**Comment by timkelty** [comment]
Closest I've gotten is merging each nested ChainedMap explicitly, but seems like there's got to be better way…

```
  const baseRule = neutrino.config.module.rules.get('baseRule');
  const newRule = neutrino.config.module.rule('newRule').merge(baseRule.entries());

  Object.keys(baseRule.uses.entries()).forEach((useId) => {
    newRule.use(useId).merge(baseRule.use(useId).entries());
  });

   newRule.test(/newTest/);
```

**Comment by edmorley** [comment]
It would seem that perhaps the easiest way would be to add support within webpack-chain, if it were seen to be something that people would use? @eliperelman thoughts?

**Comment by guanzo** [comment]
I'd like to know how to clone a plugin, and tweak some options.

**Comment by TotooriaHyperion** [comment]
Also want ability to clone the entire config spec, so I can build and publish different bundle for different platform with only one command in our cli tool.(I mean web+rn+microapp+...)

**Comment by Shayan-To** [comment]
I need some different processings for a subset of my files, so this would make my life a lot easier.
