### ISSUE TITLE
Feature Request(willing to PR): Create Relation-Graph between nested chainMap/chainSet and their methods.

### ISSUE THREAD

**Issue by mc-zone** [neutrinojs/webpack-chain#137]
As we know, `webpack-chain`'s internal code provides some nested `chainMap/chainSet` and used with their shorthand methods. For example,  the `optimization.minimizers` in v5: 

`optimization.minimizers<ChainedMap>`

https://github.com/neutrinojs/webpack-chain/blob/d124b5df6648257092becae81ceece9bef5485b8/src/Optimization.js#L7

with `optimization.minimizer<Function>` method usage:

https://github.com/neutrinojs/webpack-chain/blob/d124b5df6648257092becae81ceece9bef5485b8/src/Optimization.js#L29-L34

So we can use this neatly:
```javascript
optimization.minimizer('sb').use(sth, [xxx])
```
But in v4, people still using setter method on this point:

```javascript
optimization.minimizer([ new Sth(xxx) ])
```

It is just a tiny upgrade but actually leads to a break-change version. Some integration tools like vuejs/vue-cli#3191 can't upgrade easily unless shipped a major release. It will be a long time.

So if we can make it back-compatible, these v4 users might upgrade to v5 painlessly.

After reading the code. I found that if we can create a **Relation Graph** between the `ChainedMap/ChainedSet`  and corresponding method, like`optimization.minimizers` with `optimization.minimizer()`. Then we can provide the compatible between them internally and programmatically.

IMO,  instead of declaring them independent, we can use some binding factory to create them:

```javascript
// Optimization
this.createStoreWithAccessor(
  'minimizers',
  new ChainedMap(this),
  'minimizer',
  name => new Plugin(this, name, 'optimization.minimizer')
);
```

And record the relationship while creating:
```javascript
// ChainedMap
createStoreWithAccessor(storeName, store, accessorName, accessorFactory) {
  this[storeName] = store;
  this[accessorName] = name => store.getOrCompute(name, accessorFactory.bind(store, name));
  this.accessorGraph.set(accessorName, storeName);
}
```
Then next step, we can find and make some compatible wraps to methods depends on the `accessorGraph` records if we need.

```javascript
getOrCompute(key, fn) {
  if (this.compatible && typeof key !== 'string') {
    return this.compatibleSet(key);
  }
  if (!this.has(key)) {
     this.set(key, fn());
  }
  return this.get(key);
}

compatibleSet(args) {
  this.clear();
  args.forEach((item, index) => {
    this.getOrCompute(`__compatible_${index}__`).use(item);
  });
  return this;
}

get(key){
  if (this.compatibleMethods.has(key)) {
    const relatedStore = this.findStoreForAccessor(key);
    return relatedStore.values().map(c => c.toConfig());
  }
  return this.store.get(key);
}
```
Or provide an API to enable which methods they want to have compatible behavior manually:
```javascript
optimization._compatible(["minimizer"]);
optimization.minimizer([ new Plugin(xxx), new Plugin(xxx) ]); // works with compatibility
optimization.minimizer("myPlugin").use(MyPlugin, [xxx]); // also works
optimization.get("minimizer"); // output compatible with v4 
```

I've had some demo in my local and basically works. I'd like to make PR if it makes sense for all! 😃

**Comment by mc-zone** [comment]
cc @eliperelman @edmorley

**Comment by edmorley** [comment]
Hi sorry for the delayed reply. Thank you for raising this issue - I agree the breaking change is tricky for consumers of webpack-chain such as Vue.

Looking at the Vue CLI projects listing here, it seems like a new major version will be released some time after webpack 5's release:
https://github.com/vuejs/vue-cli/projects

...which might be a way out even though webpack 5 is now in the alpha phase.

I would be open to accepting a PR for the proposed changes above, to be released as a webpack-chain 5.x.x release. We would then remove the compatibility layer in a future webpack-chain 6 release.

@eliperelman what do you think?

Also, we should probably check that Vue CLI 3 would be willing to update to webpack-chain 5.x with this PR in place (otherwise the changes here won't help).

**Comment by mc-zone** [comment]
@edmorley Hi, Thanks for your reply!

My point is maybe we could improve the internal code to enhance compatibility about webpack-chain itself, and not only for Vue, but also for any other use cases. the changes should not bring a major release, no break-changes will be added for this propose. Just to make internal more extensible. Also, we don't have to remove it in the future.

And of course, if you think this is a premature optimization, not make any changes is also fine, these just some idea of my own.

**Comment by edmorley** [comment]
Perhaps the best way forwards is if you open a PR and we can see how invasive the solution ends up being? :-)

**Comment by mc-zone** [comment]
Hi @edmorley, I've pushed my implementation above to #141. Looking forward to hearing your advice.

**Comment by edmorley** [comment]
Closing this out for now - see https://github.com/neutrinojs/webpack-chain/pull/141#issuecomment-570630089.
