### ISSUE TITLE
Ambigious Docs for "Config plugins: modify arguments"

### ISSUE THREAD

**Issue by douglasg14b** [neutrinojs/webpack-chain#138]
The docs for the section `Config plugins: modify arguments` seem ambiguous, and don't describe exactly what is expected on the right side of the lambda.

I'm sure this is obvious to some webpack users, but it isn't for me, or anyone I've asked for help.

What exactly is expected on the right hand side of the lambda? What is a real-world example of adding an option to the `ts-loader` plugin:

```js
options: {
  appendTsSuffixTo: [/\.vue$/]
}
```

**Comment by douglasg14b** [comment]
Hi @edmorley  

Thanks for the writeup. It looks like I was using the wrong thing!. However, in the docs example there is a call to `merge`, this isn't something I have defined. I assume it's merging the objects, but I don't want to make any assumptions here.

I have added the following (the `tap` at the end) as a replacement of the options, but it causes an error `Cannot set property 'appendTsSuffixTo' of undefined`. I assume I'm setting this up wrong again?

```js
      config.module
        .rule('ts-loader')
        .test(/\.tsx?$/)
        .exclude
          .add(/node_modules/)
          .end()
        .use('ts-loader')
          .loader('ts-loader')
          .tap(options => { 
            return {appendTsSuffixTo: [/\.vue$/]} 
          }),
```

**Comment by edmorley** [comment]
Ah the `merge()` is any merging function of choice (eg [deepmerge](https://github.com/TehShrike/deepmerge)) - though that's definitely not clear without context, sorry!

Re the example above, whilst it's not the cause of the error, `.tap()` is used to modify options that have already been set elsewhere, so in that example it would be best to use `.options()` instead, as in this example:
https://github.com/neutrinojs/webpack-chain#config-module-rules-uses-loaders-creating

Re the error, when I try the example above it works for me (in creating the webpack config; I didn't try running a build), so there must be something else that wasn't pasted above that isn't working? Note that in the example above, the existing options are replaced entirely by the return value from the `.tap()`, so if you want to preserve existing options whilst adding/overriding `appendTsSuffixTo`, use something like:

```js
        .use('ts-loader')
          .tap(existingOptions => { 
            return {
              ...existingOptions,
              appendTsSuffixTo: [/\.vue$/],
            };
          })
```

...or for something even shorter, the `return` statement can be omitted if the arrow function brackets are removed:

```js
        .use('ts-loader')
          .tap(existingOptions => {
              ...existingOptions,
              appendTsSuffixTo: [/\.vue$/],
          })
```

When debugging you may find it helpful to output the generated webpack config using eg:
`console.log(config.toString())`

Which gives output like:

```
{
  module: {
    rules: [
      /* config.module.rule('ts-loader') */
      {
        test: /\.tsx?$/,
        exclude: [
          /node_modules/
        ],
        use: [
          /* config.module.rule('ts-loader').use('ts-loader') */
          {
            loader: 'ts-loader',
            options: {
              appendTsSuffixTo: [
                /\.vue$/
              ]
            }
          }
        ]
      }
    ]
  }
}
```

See here for more information:
https://github.com/neutrinojs/webpack-chain#inspecting-generated-configuration

**Comment by douglasg14b** [comment]
Thanks for all the info! I really appreciate it.

This should be a great help to anyone else that finds this thread via google. the `omit.includes is not a function` was my fault (notice the `,` at the end of my chain?). With that removed this works as expected.

**Comment by edmorley** [comment]
Reopening for tracking improving the docs.
