### ISSUE TITLE
How to delete or modify externals ?

### ISSUE THREAD

**Issue by lili21** [neutrinojs/webpack-chain#150]
```javascript
const Config = requirej('webpack-chain')
const config = new Config()
config.externals({
    'react': 'React',
    'react-dom': 'ReactDOM'
  })
```

how to modify or delete externals in webpack chain way ?

**Comment by eliperelman** [comment]
The configuration is a `ChainedMap`, so you should be able to use `delete` to perform the removal:

```js
config.delete('externals');
```

Hope that helps. Feel free to re-open if that doesn't answer your question.

**Comment by edmorley** [comment]
Also if you can think of any changes to the docs that could make this clearer, we'd love ideas (or PRs hehe) :-)
