### ISSUE TITLE
Modify splitChunks options

### ISSUE THREAD

**Issue by johannes-z** [neutrinojs/webpack-chain#166]
I'm trying to add `automaticNameDelimiter: '__'` to `config.optimization.splitChunks`. None of the following two calls work however:

```js
    config.optimization.splitChunks.tap(args => [
      ...args,
      { automaticNameDelimiter: '__' },
    ])
    // or ...
    config.optimization.splitChunks().tap(args => [
      ...args,
      { automaticNameDelimiter: '__' },
    ])
```

**Comment by eliperelman** [comment]
`splitChunks` is a setter: https://github.com/neutrinojs/webpack-chain#configuring-optimizations-shorthand-methods

```js
config.optimization.splitChunks({ automaticNameDelimiter: '__' });
```

If you want to merge with the existing, you'll need to get that value out for merging:

```js
config.optimization.splitChunks({
  ...config.optimization.get('splitChunks'),
  automaticNameDelimiter: '__'
});
```

Feel free to reopen if that doesn't work. Thanks!
