### ISSUE TITLE
how to create exclusive rule?

### ISSUE THREAD

**Issue by leftstick** [neutrinojs/webpack-chain#181]
I would like to create a new rule for `.gql` files with [graphql-tag/loader](https://github.com/apollographql/graphql-tag#webpack-preprocessing-with-graphql-tagloader). The config as below:

```javascript
config.module
  .rule('graphql')
    .test(/\.gql$/)
    .exclude
      .add(/node_modules/)
      .end()
    .use('graphql')
    .loader('graphql-tag/loader')
```

For some reason, it's not working, following code

```javascript
import content from './user.gql'
```

always return a `base64` string for me which is not correct(should be an object). Once i use [inline](https://webpack.js.org/concepts/loaders#inline) way to import the file as below

```javascript
import content from '!graphql-tag/loader?modules!./user.gql'
```

everything works fine.

Is there a way to create a new rule with all other configurations disabled?

**Comment by leftstick** [comment]
Closed since i found the rule which affected my configuration

**Comment by Jerry-Ran** [comment]
Hi~I have the same quesion with creating a custom loader. 

Could you tell how to settle this problem?

**Comment by leftstick** [comment]
@Jerry-Ran hi, no silver bullet, just boring exclusion method. Remove every rule individually and inspect the result, that's the way I chose. The root cause in my case was another rule with an inaccurate condition used by `.gql` as well

**Comment by Jerry-Ran** [comment]
> @Jerry-Ran hi, no silver bullet, just boring exclusion method. Remove every rule individually and inspect the result, that's the way I chose. The root cause in my case was another rule with an inaccurate condition used by `.gql` as well

Thanks for your reply, I tryid ,but it looks like a challenge to remove rules one by one in our project.It took me a lot, whatever thanks a lot again
