### ISSUE TITLE
Why does the webpack-chain not provide the optimization.chunkIds option?

### ISSUE THREAD

**Issue by chentianyuan** [neutrinojs/webpack-chain#190]
![image](https://user-images.githubusercontent.com/24367006/61619400-5d81a380-aca1-11e9-9106-4b9de9dc8710.png)

**Comment by Airkro** [comment]
`webpack-chain` does not always follow all the options of `webpack`, but `config.optimization` is [ChainedMap](https://github.com/neutrinojs/webpack-chain#chainedmap). You can using this:

```js
config.optimization.set('chunkIds', yourOptions);
```

**Comment by edmorley** [comment]
We'd accept a PR adding native support for `chunkIds` too :-)
