### ISSUE TITLE
How to set 'entry' to be a function?

### ISSUE THREAD

**Issue by bigmeow** [neutrinojs/webpack-chain#191]
example:
```js
const  getEntrys = function () {}
module.exports = {
    entry: getEntrys,
    mode: 'development'
}
```

And I tried the following code but it is invalid, the 'entry' not support function type

```js
const config = new Config()
config.merge({
  mode: 'development',
  entry: function () {
    return {}
  }
})

console.log(config.toConfig())
```

hope your help, TKS

**Comment by edmorley** [comment]
Dynamic entry points are not yet supported, though a PR to add support would be gladly accepted :-)

Forward duping to #200.
