### ISSUE TITLE
How do I reorder the webpack loaders ?

### ISSUE THREAD

**Issue by hamza-eljaouhari** [neutrinojs/webpack-chain#193]
Hello

I'm making a Vue.js project initiated from the command line.

It already has a configuration of loaders and I want to insert my own loaders at the start of the "rules" array or at a specific point of this array.

How do I acheive that ?

Here are my current configuration and output

output.js : [output.txt](https://github.com/neutrinojs/webpack-chain/files/3492722/output.txt)

vue.config.js : [vue.config.txt](https://github.com/neutrinojs/webpack-chain/files/3492733/vue.config.txt)

Thank you

**Comment by yordis** [comment]
I may be wrong about this, but today the implementation is kind of limited, https://github.com/neutrinojs/webpack-chain/issues/113

Depending on your use case may be possible.

I did some work on this:

- https://github.com/straw-hat-team/javascript/blob/develop/packages/libraries/chainable-config/src/orderable-chained-map.ts
- https://github.com/straw-hat-team/javascript/blob/fb7e2496f63761af167a016dec0a1ccef0101195/packages/libraries/chainable-config/src/chained-map.ts#L72-L92

But I think it will require some breaking changes, I am not sure if @edmorley would be opened to some breaking changes to tackle complex scenarios.
