### ISSUE TITLE
Can I set the `alias` with an array?

### ISSUE THREAD

**Issue by lemon-clown** [neutrinojs/webpack-chain#194]
in my tsconfig.json, I can specify path alias such as following:
```json
"baseUrl": ".",
"paths": {
  "@/*": [ "src/main/*", "src/resources/*" ]
},
```
and then, I can import resource file 'src/resource/image/log.png' as '@/image/logo.png', and at the same time, I aslo can import file 'src/main/util/fs-util.ts' as '@/util/fs-util'.

I tried it, but got this error message:
![image](https://user-images.githubusercontent.com/14110615/63253898-513f3500-c2a5-11e9-9896-f7d67710f75f.png)

I hope I made myself clear, thank you!

**Comment by MonchiLin** [comment]
Any progress ?
