### ISSUE TITLE
Dynamic entry points not supported?

### ISSUE THREAD

**Issue by nerdoc** [neutrinojs/webpack-chain#200]
Webpack allows use of dynamic entry points by passing a function to "entry" instead of a fixed string or list, see [here](https://webpack.js.org/configuration/entry-context/#dynamic-entry).
It seems that this is not possible, as webpack-chain has only hardcoded support for strings or lists - right?
Did I miss something here?
Or is that feature not planned?

**Comment by edmorley** [comment]
Yeah glancing now, it looks like webpack-chain doesn't yet support that. Pretty much every webpack configuration feature has to be explicitly added to webpack-chain, so if something's missing it normally just means we haven't gotten around to it, or weren't aware it was missing.

I don't have a huge amount of time to spend on webpack-chain at the moment, so won't be working on this myself, however a PR with tests would be welcome :-)

**Comment by nerdoc** [comment]
As my Js skills are those of a monkey sitting in front of a laptop, I'm afraid I can't be of great help here...
