### ISSUE TITLE
add url-loader to .json files

### ISSUE THREAD

**Issue by zzuzsj** [neutrinojs/webpack-chain#201]
I add json-loader to .json files.But something error happend to the config.
![image](https://user-images.githubusercontent.com/20783807/64759958-1c07c900-d56b-11e9-8394-fa2e40755115.png)
![image](https://user-images.githubusercontent.com/20783807/64759987-2c1fa880-d56b-11e9-850a-6ab01bf40b17.png)
![image](https://user-images.githubusercontent.com/20783807/64759996-30e45c80-d56b-11e9-8249-5111889f198b.png)

**Comment by edmorley** [comment]
This issue doesn't seem specific to webpack-chain. Unfortunately we don't really have the spare time to debug general webpack issues. I hope you got/get this figured out though! :-)
