### ISSUE TITLE
how to add a preloader use webpack-chain

### ISSUE THREAD

**Issue by FanJfly** [neutrinojs/webpack-chain#208]
Hello, I have a problem,I add istanbul-loader before my vue-loader,I try use enforce(),pre(),but It's not work, and I dont kow why, somebody have some idea?  
this is my old config:
webpack : {
  modlue : {
    loaders: [
      {
         test: /\.vue$/,
         loader: 'vue-loader',
        options: {
           preLoaders: {
             js : 'istanbul-instrumenter-loader?esModules=true'
           }
        }
      }
    ]
  }
}
it's work

but I change it with webpack-chain : 
chainWebpack: (config) => {
   config.module
   .rule("istanbul")
   .use("istanbul")
   .loader("vue-loader")
   .end()
   .enforce('pre')
   .use("test")
   .loader("istanbul-instrumenter-loader")
   .end();
}
or 
chainWebpack: (config) => {
   config.module
   .rule("istanbul")
   .use("istanbul")
   .loader("vue-loader")
   .options({rules: { js : 'istanbul-instrumenter-loader?esModules=true'}})
   .end();
}
both can't work well, and I dont kow why, somebody have some idea?  
istanbul-instrumenter-loader not preLoaders

**Comment by yinsang** [comment]
`config.module
      .rule('vue')
      .use('vue-loader')
        .loader('vue-loader')
        .tap(options => {
          // 修改它的选项...
          console.log(options)
          const addCoverage = {
            ...options,
            preLoaders: {
              js: 'istanbul-instrumenter-loader?esModules=true'
          }
          }
          return addCoverage
        })`
may helps u.

**Comment by FanJfly** [comment]
> ```
> config.module
>       .rule('vue')
>       .use('vue-loader')
>         .loader('vue-loader')
>         .tap(options => {
>           // 修改它的选项...
>           console.log(options)
>           const addCoverage = {
>             ...options,
>             preLoaders: {
>               js: 'istanbul-instrumenter-loader?esModules=true'
>           }
>           }
>           return addCoverage
>         })
> ```
> 
> may helps u.

thx，it's work, I find it‘s not  my  webpack-chain writing error,  maybe it's because I use ts.
