### ISSUE TITLE
does webpack-chain config.module.exclude support regular?

### ISSUE THREAD

**Issue by saysmy** [neutrinojs/webpack-chain#211]
```
config.module
      .rule('compile')
      .test(/\.js$/)
      .exclude
         .add(/node_modules/)
         .end()
      .use('babel')
         .loader('babel-loader')
         .options({
              presets: [
              ['@babel/preset-env', { modules: false }],
         ],
      });
```

config with this，but not work， why?

```
.exclude
         .add(/node_modules/)
         .end()
```

**Comment by saysmy** [comment]
好的~~收到~~

**Comment by edmorley** [comment]
GitHub sadly doesn't allow including a comment when mass-closing issues (nor setting the "not planned" closure status) - so unfortunately I couldn't add a comment explaining why to every issue. The reason for closing is this:
https://github.com/neutrinojs/webpack-chain/issues/358
