### ISSUE TITLE
How do I modify the LoaderOptionsPlugin configuration?

### ISSUE THREAD

**Issue by cnguu** [neutrinojs/webpack-chain#214]
I want to set global variables using LoaderOptionsPlugin, but I don't know how to write

```js
plugins: [
    new webpack.LoaderOptionsPlugin({
      options: {
        stylus: {
          import: [
            path.resolve(__dirname, './src/_styles/variables.styl')
          ]
        }
      }
    })
  ]
```

**Comment by edmorley** [comment]
Hi! Adding plugins with options is documented here:
https://github.com/neutrinojs/webpack-chain#config-plugins-adding

Does that help? :-)
