### ISSUE TITLE
Support a single webpack entry

### ISSUE THREAD

**Issue by joeldenning** [neutrinojs/webpack-chain#230]
It is possible to have the webpack [`entry`](https://webpack.js.org/configuration/entry-context/#entry) be a string instead of an object. However, webpack-chain doesn't seem to support this, as shown in the following code:

https://github.com/neutrinojs/webpack-chain/blob/573553e5feaa8a08f12ca3bf7b0f44d91054d269/src/Config.js#L131-L135

It's also possible to support an object where the values are strings, instead of arrays of strings.

Is this something you'd be open to changing? Am happy to discuss API and submit a PR for it.

**Comment by edmorley** [comment]
Looking at the webpack docs ([concepts](https://webpack.js.org/concepts/entry-points/); [config](https://webpack.js.org/configuration/entry-context/)) and [config schema](https://github.com/webpack/webpack/blob/627510d7e72582463d76608fe3cda5a70ea17a12/schemas/WebpackOptions.json#L31-L95), it looks like the accepted forms of `entry` are:

1) Single entry shorthand with single filename:

```js
module.exports = {
  entry: './foo.js',
};
```

2) Single entry shorthand with an array of filenames:

```js
module.exports = {
  entry: [
    './foo.js',
    './bar.js',
  ],
};
```

2) Object form with single filename:

```js
module.exports = {
  entry: {
    main: './foo.js',
  },
};
```

3) Object form with an array of filenames:

```js
module.exports = {
  entry: {
    main: [
      './foo.js',
      './bar.js',
    ],
  },
};
```

4) Dynamic entry(function):

```js
module.exports = {
  entry: () => {
    // Function must return one of the forms above (entry object, string, or array)
    // or a promise to these things.
  },
};
```

---

Returning back to webpack-chain, currently to set the entry point(s) one must use either:

```js
config.entry('main')
  .add('./foo.js');
```

or:

```js
const Config = require('webpack-chain');
const config = new Config();

config.merge({
  entry: {
    main: ['./foo.js']
  },
});
```

There seem to be as few problems with this:

1) There is no support for dynamic (function) entry point definitions at all (filed as issue #200)
2) The schema supported by `.merge()` is quite limited (though merge has many other issues; I wish we could just remove the feature entirely - not really sure many of the use-cases for it make sense too?)
3) When the configuration is generated using `.toConfig()`, it's always output in the long form (form 3 above), even if there are only single entries/filenames. Though perhaps some people would prefer consistency, and if the config is ever diffed, always using the long form reduces diff churn.
4) When specifying the config via `config.entry()` one always has to set an entry name (though same could be said for plugins/rules/... I guess?).

@joeldenning was your main concern around (4)?

**Comment by joeldenning** [comment]
> was your main concern around (4)?

No - my main concern is about (1). As far as I can tell, the following webpack config is not currently possible to construct with webpack chain:

```js
module.exports = {
  entry: 'src/index.js'
}
```

**Comment by edmorley** [comment]
Ah sorry I used numbers for both the "accepted webpack config output" forms and the "there are a few problems with this" list. I've changed the former to use A-E instead of numbers.

By "was your main concern around (4)" I meant more was the issue relating to inputting **to** webpack-chain or the output format **from** webpack-chain, or something else?

**Comment by joeldenning** [comment]
Ah I see now. Yes, my main concern is that webpack-chain's `entry` and `entryPoints` requires all entries to have a name.

I'm looking to create the webpack config as shown in A)

**Comment by edmorley** [comment]
Sorry I haven't replied yet - need to sit down and think about this some more when I have more solid block of time free :-)

**Comment by joeldenning** [comment]
👍 looking forward to hearing your thoughts on it

**Comment by chym123** [comment]
I need this format of entry too
```
module.exports = {
  entry: {
    main: './foo.js',
  },
};
```
If you use the 'B' or 'D' format you replied, when I compile a 'umd' lib
```
output: {
    filename: '[name].js',
    library: '__pages',
    libraryTarget: 'umd',
},
```
you will receive a number instead of the lib. This is part of the compilation result
```
window["__pages"] = (window["webpackJsonp_pages"] = window["webpackJsonp_pages"] || []).push([["your entries"], ...])
```

Looking forward to your help！

**Comment by homersimpsons** [comment]
Hello, I have kind of this issue, but I would like to use an object instead of an array for my entries. My goal is to have something like:

```
entry: {
  app: { import: 'src/main.js', filename: 'main.js' }
}
```

My main try is
```
config.entry('app)
  .set('import', 'src/main.js')
  .set('filename', 'main.js')
```

But of course this does not work.

To me the datastructure of an `entryPoints[key]` should always be an object. It could then easily be transformed to a more concise structure if applicable.

The `values()` function may have to be overloaded.

**Comment by buksy90** [comment]
Hi, I'd like to set `library` property on my entry point

I'm trying with following

```
config.entryPoints.set(`widget`, {
          import: `./src/pages/widget/index.ts`,
          library: {
            name: 'widget',
            type: 'jsonp',
          },
        });
```

But there is following error `TypeError: entryPoints[key].values is not a function`

**Comment by homersimpsons** [comment]
For the record, this issue is most likely not complete but the project is now abandoned #358.

To all the maintainers, thank you for your contributions !

**Comment by edmorley** [comment]
@homersimpsons Hi! Yeah sadly the GitHub mass-issue closing UI doesn't allow for choosing the closure-type of "Not planned" or leaving a comment (mentioning #358) - which meant I had to mass close as "Completed".
