### ISSUE TITLE
Support devServer.sockHost, devServer.sockPath, and devServer.sockPort

### ISSUE THREAD

**Issue by joeldenning** [neutrinojs/webpack-chain#231]
Thanks for your work on this project - I enjoy  using it.

I would love to see [devServer.sockHost](https://webpack.js.org/configuration/dev-server/#devserversockhost), [devServer.sockPort](https://webpack.js.org/configuration/dev-server/#devserversockport), and [devServer.sockPath](https://webpack.js.org/configuration/dev-server/#devserversockpath) supported in webpack chain. As far as I can tell, they currently are not supported at all.

**Comment by edmorley** [comment]
Hi! Thank you for filing this issue - I agree webpack-chain should support these. Would you be open to creating a PR for it? :-)

**Comment by joeldenning** [comment]
I created #238 to resolve this. In doing so, I realized that it was already possible to set the sockHost, sockPath, and sockPort via `config.devServer.set('sockHost', '8080')`. However, my PR adds the shorthand methods for them: `config.devServer.sockHost('8080')`

**Comment by edmorley** [comment]
Awesome, thank you :-)

> I realized that it was already possible to set the sockHost, sockPath, and sockPort via `config.devServer.set('sockHost', '8080')`

Yeah the long form is useful to work around lack of support, but adding the shorthand methods longer term is the best approach.
