### ISSUE TITLE
How can I export an array as config instead of a plain object?

### ISSUE THREAD

**Issue by regreceive** [neutrinojs/webpack-chain#245]
I need multiple configs just like https://github.com/webpack/webpack/issues/731, how to achieve it when using webpack-chian?

**Comment by edmorley** [comment]
@regreceive Hi! I would create multiple webpack-chain instances, and export them in an array. eg:

```js
const Config = require('webpack-chain');

const config1 = new Config();
const config2 = new Config();

// Do things with `config1` and `config2`

module.exports = [config1.toConfig(), config2.toConfig()];
```
