### ISSUE TITLE
Proposal: introduce Preset like feature

### ISSUE THREAD

**Issue by donnysim** [neutrinojs/webpack-chain#248]
Hi, lately I've been thinking of a way to speed up ways of getting necessary features/config of webpack up and ready faster and reduce the boilerplate and was thinking about a some kind of presets that could work around webpack-chain. The main goal is that a Preset can install and configure dependencies when building the config using webpack-chain, something along these lines:

```js
const Config = require('webpack-chain');
const config = new Config();

config.presets.install/add('eslint', new Eslint());
```

where the Eslint Preset could look something like (note the syntax is different from webpack-chain because this is my "laying things around how I'd imagine it would look/work" kind of thing):

```js
const Preset = require('../config/preset');

module.exports = class extends Preset {
  constructor(config = {}) {
    super();
    this._config = Object.assign({
      friendlyFormatter: true,
      test: /\.js$/u,
    }, config);
  }

  install(config) {
    config
      .dependencies
        .add('eslint-loader')
        .when(this._config.friendlyFormatter, dependencies => {
          dependencies.add('eslint-friendly-formatter');
        })
        .end()
      .module.rule('eslint', rule => {
        rule
          .enforce('pre')
          .test(this._config.test)
          .exclude.add(/node_modules/u).end()
          .use('eslint').loader('eslint-loader').tap(useConfig => {
            if (this._config.friendlyFormatter) {
              if (!useConfig.options) {
                useConfig.options = {};
              }

              useConfig.options.formatter = require('eslint-friendly-formatter');
            }
          });
      });
  }
};
```

As far as I understand there would be couple required changes: 
 - config should not be altered when building the config so that multiple `.toConfig()` can be called without side effects (probably?);
 - introduce `tap` helper, where the resulting configuration of a segment is passed through a pipeline that can further alter the built config - this is necessary because some configurations require external dependencies that are not yet installed or based on options passed to the Preset;
 - the main `toConfig` function needs to be asynchronous to allow waiting to dependency installation.

This would allow to quickly setup a project or playground without having to remember and deal with a bunch of dependencies. The cli output could looks something similar:

```bash
 INFO  Additional dependencies must be installed. This will only take a moment...
 INFO  Running: npm install eslint-loader eslint-friendly-formatter --save --save-exact --loglevel=error

 INFO  The following packages have been installed and saved to your package.json dependencies list:
 INFO   - eslint-loader
 INFO   - eslint-friendly-formatter

```

What do you think?

**Comment by edmorley** [comment]
Hi! What you're describing sounds a bit like https://neutrinojs.org/ and its preset system, which wraps webpack-chain :-)

**Comment by donnysim** [comment]
And I search for one and could only find webpack-presets 😅. Gonna close this and go check it out, hopefully it's what I'm loking for. Thanks, and great work on webpack-chain!

**Comment by donnysim** [comment]
Sadly, just by reading the documentation and trying it out for a bit, not a fan - not really how I expected it to work and it just leaves it as yet another unnecessary abstraction layer in my case as the dependency resolution is closer to "add dependencies to package.json, publish you preset, and require it in your project for it to install them" which is not what I aim for. What I'm seeking is for it to be able to resolve dependencies locally without having to pull any other packages for something to work - as simple as:

```js
const Config = require('webpack-chain');
Config.dependencies.add('eslint-loader');
```

etc. and it installs it on first run. Main reasons being - I'll never install any external presets - that just screams configuration problems and possibly unexpected updates/outcomes, and I prefer having full control of the configuration, living inside the project even if it means copy paste from project to project, except I wouldn't need to cherry pick the dependencies from package.json.

**Comment by edmorley** [comment]
Hi :-) I agree it's another abstraction layer and those have trade-offs, so can understand why people may wish not to use it.

I think the problem is that installing JS dependencies on first run is something that's quite different from how the JS ecosystem normally works. I would go as far as saying that managing dependencies outside of package.json would be seen as many as an anti-pattern. 

It sounds like your use-case of wanting re-usable code that manages dependencies too, is already filled by creating a JS package that uses webpack-chain? That package could either be vendored in each project that uses it (and have the repo root package.json reference the package using a relative path), or else as an external package/repo.

**Comment by donnysim** [comment]
I do agree that managing dependencies outside of package.json is kind of anti-pattern'ish, but what I ment by installing them, it would add them to the developers package.json as if you're doing the usual `npm install my-package`. It's just one headache less for the developer so that we don't have to go scramble what dependencies we need or forgot to include to get this "thing" (project setup) working.

There's this "oh god, I'd have to configure webpack again" every time you have to do it floating around webpack, so just wishing I could do:

```
npm install webpack-chain
npm run build
```
where the webpack config could be:
```js
const Config = require('webpack-chain');
const config = new Config();

config.dependencies.add(['webpack', 'webpack-cli']);
config.preset.add(new MyEslintPreset()); // vue, babel and so on

... the usual entry, output stuff
```

and I'm done, I can go play around with whatever I need, all dependencies added to my package json for me to "tweak" (like update versions etc). I'm not locked into some other packages dependencies and so on.

Someday it will come true 😄
