### ISSUE TITLE
r.toConfig is not a function

### ISSUE THREAD

**Issue by temple** [neutrinojs/webpack-chain#264]
When launching `vue-cli-service build` webpack prints out:  
```
-  Building for production... ERROR  TypeError: r.toConfig is not a function
```
## Expected Behavior
Any valid webpack configuration object may be converted to a valid `webpack-chain` config sub-object in a ChainedMap or ChainedSet depending on the place where the object is _set_.

## Current Behavior
Documentation says any type (`*`) of value is allowed as a second argument when calling `ChainedMap.set('key', value)`.

## Possible Solution
Modify the _README.md_ and open branch having the expected behaviour for goal.

## Steps to Reproduce

1. Create a _vue-cli_ project by following the steps described at https://cli.vuejs.org/guide/creating-a-project.html
2. Create a `vue.config.js` file with this content
    ```javascript
    module.exports = {
      chainWebpack: config => {
        config.module.rules.set('svg', { test: /\.svg$/i, issuer: /\.vue$/i, use: 'vue-svg-loader' })
      }
    }
    ```
3. Add a "build" script to `package.json` like this
    ```
    scripts: {
      "build": "vue-cli-service build"
    }
4. Execute `npm run build`

## Context (Environment)
Windows 10 64b.  
nodeJs v12.16.3
npm v6.14.5
vue v2.9.6
@vue/cli v4.4.1
@vue/cli-service v.4.4.1
webpack v4.43.0 
webpack-chain v6.4.0

## Detailed Description
The error occurs when building a _vue@2.9.6_ project, using _webpack@4.43.0_ and _webpack-chain@6.4.0_, pretending to _set_ a _rule_ via _webpack-chain_ by passing a _webpack_ valid _rule object_ as the second parameter.  

> Template taken from https://raw.githubusercontent.com/stevemao/github-issue-templates/master/bugs-only/ISSUE_TEMPLATE.md

**Comment by edmorley** [comment]
@temple Hi! The type definition for `rules` says that the value of the ChainedMap must be `Rule`:
https://github.com/neutrinojs/webpack-chain/blob/bebcf39e1a80fb1333e15eb930f74b1ba45653b2/types/index.d.ts#L228

Also whilst the `rules` ChainedMap is exposed to end users, it's anticipated that most of the time the individual rules will be accessed as described here:
https://github.com/neutrinojs/webpack-chain#config-module-rules-shorthand-methods

...and when a new rule is created using that API, the value of the key added to the `rules` ChainedMap is a new instance of `Rule`, not an object:
https://github.com/neutrinojs/webpack-chain/blob/dd229b51c9840532987d193072307ce3ff138f1c/src/Module.js#L20

As such the API usage described in this issue isn't valid, though I can see why it might it could seem that way.

To merge in existing webpack objects, you need `.merge()` instead:
https://github.com/neutrinojs/webpack-chain#merging-config
https://github.com/neutrinojs/webpack-chain/blob/dd229b51c9840532987d193072307ce3ff138f1c/src/Module.js#L32-L46

If you can think of a way to make this situation clearer in the docs, we'd gladly accept a PR :-)
