### ISSUE TITLE
Webpack 5 support

### ISSUE THREAD

**Issue by virajsanghvi** [neutrinojs/webpack-chain#266]
Hi, I was just wondering if there were plans to support webpack 5 or if that was going to wait until its official release. Thanks!

**Comment by edmorley** [comment]
@virajsanghvi Hi! I'd be happy to accept a PR to add support before the webpack 5 final release. However I don't have much time to work on webpack-chain or Neutrino at any more, so we'd need someone from the community to open a PR :-)

**Comment by gpetrov** [comment]
@edmorley  Does this makes webpack-chain totally unusable with webpack 5? Or it is just that few new options are not supported bit it can read and write webpack 5 configs just as well?

**Comment by edmorley** [comment]
@gpetrov The latter :-)

**Comment by gpetrov** [comment]
Great to hear! I was just searching for a tool to read/write webpack config and webpack-chain seems to fit perfectly, but cooperation with webpack 5 is essential.

Could you identify a bit the parts that might need changes for webpack 5 - I will be glad to help out.

**Comment by edmorley** [comment]
I would start by reading through:
https://webpack.js.org/blog/2020-10-10-webpack-5-release/

...and seeing if there are any options added/removed that are essential for a webpack config, and not currently set-able with webpack-chain :-)

**Comment by concubicycle** [comment]
I think this is a duplicate - I saw another issue for Webpack 5 support here. But regardless, it's a shame we don't have it yet. there are some libraries like postcss-loader which now depend on Webpack 5, and to get them working with Neutrino, you have to install an older version of the loader.

**Comment by edmorley** [comment]
Hi! I'm not actively working on any project that uses webpack, so haven't used Neutrino or webpack-chain for some time. As such it's hard to justify spend time maintaining them. I'd hoped there would be more interest from the rest of the community in helping with maintenance (particularly given the Vue ecosystem uses webpack-chain), but there hasn't been so far.

For webpack 5 support to happen, someone will need to volunteer to open a PR :-)

**Comment by sodatea** [comment]
Hi, @edmorley I'm maintaining Vue CLI and I would love to help triage issues and review PRs in this repository :)

As for actual coding tasks, I may not have large pieces of time to dive into the codebase. But I'll try my best to help.

**Comment by edmorley** [comment]
@sodatea Thank you for the offer to help. Adding webpack 5 support will likely require a few people to help out - someone to open a PR and someone who is up to date with webpack 5 changes to review. Once the PR is open an initial review from someone else has taken place, I'm happy to have one last glance over before merging and releasing a new webpack-chain version - however just to set expectations, I won't have time to open the PR myself or perform the primary review. However I will definitely do anything I can on the release side.

**Comment by edmorley** [comment]
Also given the Travis CI situation (no more credits being given to OSS projects), someone will need to convert the CI to either GitHub Actions or Circle CI. The Neutrino project looks like it's going to start using GitHub Actions (neutrinojs/neutrino/pull/1663) so that might be the best option. I don't have time to work on this, but would be able to review a PR.

**Comment by concubicycle** [comment]
I'm up for it.. I have a little time these days.

**Comment by githoniel** [comment]
@concubicycle  how is your work now?  

I will implement it because my company's project also needs this

**Comment by concubicycle** [comment]
> @concubicycle  how is your work now?  
> 
> I will implement it because my company's project also needs this

Ah, my bad, I've been really busy this past month. Started a job

**Comment by githoniel** [comment]
> > @concubicycle  how is your work now?
> > I will implement it because my company's project also needs this
> 
> Ah, my bad, I've been really busy this past month. Started a job

 never mind, let me try this

**Comment by januwA** [comment]
If you don’t update to support webpack 5, this will be eliminated. Now many loaders have been updated to webpack 5

**Comment by githoniel** [comment]
> Now many loaders have been updated to webpack 5

Although my PR hasn't been merged yet, it work fine，edmorley has been very busy lately.s

**Comment by robothot** [comment]
about progress

- https://github.com/neutrinojs/webpack-chain/pull/297
- https://github.com/neutrinojs/webpack-chain/pull/280

**Comment by closertb** [comment]
> > Now many loaders have been updated to webpack 5
> 
> Although my PR hasn't been merged yet, it work fine，edmorley has been very busy lately

is plan to build a beta version recently ？？

**Comment by kingyue737** [comment]
> Hi, @edmorley I'm maintaining Vue CLI and I would love to help triage issues and review PRs in this repository :)
> 
> As for actual coding tasks, I may not have large pieces of time to dive into the codebase. But I'll try my best to help.

Is `chainWebpack` of `vue.config.js` still available in vue cli5?

**Comment by yorickshan** [comment]
any updates?

**Comment by chemparparokke** [comment]
> Is `chainWebpack` of `vue.config.js` still available in vue cli5?

As I see, it is still available, but missing some config features. For example it is impossible now to set `externalsPresets` using webpack-chain. Maybe there are more limitations :thinking:

**Comment by edmorley** [comment]
I marked the wepack-chain package on npmjs.org as deprecated on 18th December, to more accurately reflect the current state of the project. The package can still be used but now a deprecation warning is shown when it is installed.

**Comment by edmorley** [comment]
Closing since this project is no longer maintained:
https://github.com/neutrinojs/webpack-chain/issues/358
