### ISSUE TITLE
Create a convertor which will automatically transform webpackConfig into chainWebpack syntax

### ISSUE THREAD

**Issue by ttodua** [neutrinojs/webpack-chain#281]
So many people needs this feature, would be excellent if it will be done. At this moment, we have to manually learn how to rewrite webpack.config.js into chainWebpack syntaxes (i.e. for Vue-Cli or alike)

**Comment by timkelty** [comment]
Love this idea!

**Comment by edmorley** [comment]
Duplicate of #272
