### ISSUE TITLE
Type DevTool maybe need compatible webpackv5

### ISSUE THREAD

**Issue by simonwong** [neutrinojs/webpack-chain#298]
## Problem

**package.json**

```json
"dependencies": {
  "webpack": "^5.36.2",
  "webpack-chain": "^6.5.1",
}
```

**webpack.config**
```ts
config.devtool('cheap-module-eval-source-map')
```

when i run code like`webpack(config.toConfig())`， webpack throw Error

```
ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.devtool should match pattern "^(inline-|hidden-|eval-)?(nosources-)?(cheap-(module-)?)?source-map$".
   BREAKING CHANGE since webpack 5: The devtool option is more strict.
   Please strictly follow the order of the keywords in the pattern.
```

## Temporary solution

Now, i changed webpack.config

```ts
config.devtool('eval-cheap-module-source-map' as Config.DevTool)
```

Webpack can work normally.

## Issue

I used `as Config.DevTool`, because the type `DevTool` not support pattern `/^(inline-|hidden-|eval-)?(nosources-)?(cheap-(module-)?)?source-map$/`

I don't know how to change the type `DebTool`, so submit this issue

**Comment by edmorley** [comment]
Hi! This is not a webpack-chain issue. Webpack 5 is more strict about what values can be set for `devtool`.
It looks like either your code, or a tool/library you are using is setting a `devtool` value that is invalid for webpack 5.
Either your code or the tool/library in question will need updating.
