### ISSUE TITLE
the allowedHosts can't set 'all'

### ISSUE THREAD

**Issue by yellowbeee** [neutrinojs/webpack-chain#310]
I use `webpack-chain` to set allowedHosts

This is my setting
`
config.devServer.allowedHosts.add('all')
`

it will change to `['all']`，but the parameter type received by webpack-dev-server is 'all'
https://github.com/webpack/webpack-dev-server/blob/cce64d80e6326740af36b33d2bc0a0b9c77bd972/lib/Server.js#L1609

**Comment by lamovv** [comment]
请问，此问题是否在跟进修复呢？
