### ISSUE TITLE
How to add polyfills?

### ISSUE THREAD

**Issue by rob4226** [neutrinojs/webpack-chain#313]
Hi,
Webpack 5 doesn't include Node polyfills by default as described be the below error:

```powershell
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }
```
[@nativescript/webpack](https://www.npmjs.com/package/@nativescript/webpack) now uses `webpack-chain` for its webpack5 configs and I am trying to learn how to use it.  I was trying to do something like `config.resolve.fallback.set("crypto", require.resolve("crypto-browserify")` but there doesn't seem to be a `fallback` property.  How do you add Node polyfills using `webpack-chain`?  Thank you.

**Comment by simon300000** [comment]
Try `config.resolve.set('fallback', { what you want })`?

**Comment by rob4226** [comment]
Great that worked! Here's what I used to include some polyfills that Webpack 5 no longer includes by default, in case it helps anyone else:
```npm i buffer crypto-browserify util stream-browserify```

```javascript
config.resolve.set('fallback', {
  Buffer: require.resolve('buffer'),
  crypto: require.resolve('crypto-browserify'),
  util: require.resolve('util/'),
  stream: require.resolve('stream-browserify'),
});
```

I also needed to use the `ProvidePlugin` that comes with Webpack for `Buffer` bc some packages were using the global Node `Buffer` instead of import/requiring it, so the above wasn't helping in those cases.

```javascript
config
  .plugin('buffer') // <-arbitrary name to give this plugin entry I guess?
  .use(require.resolve('webpack/lib/ProvidePlugin'), [
    { Buffer: ['buffer', 'Buffer'] },
  ]);
```
