### ISSUE TITLE
When using vue as Multi Page Application, components in each entry point's internal directory cannot be used in common

### ISSUE THREAD

**Issue by Dailyscat** [neutrinojs/webpack-chain#319]
I am using vue as a multi page application. I refer to the built bundle and use thymeleaf to create and render each page.

At this time, if I try to use the views/brand/management/component/BrandSearch.vue component in two view files under views/, a blank page is displayed.

However, in the webpack dev server, the screen is displayed even if I use it as above.

And again, if I place the brandSearch component in vue/components at the top instead of under views/ and use it publicly, the screen is displayed again at this time.

Here is a summary of my questions

1. Why is the screen not displayed when reusing components in the views/ directory when referring to a bundle in thymeleaf?

2. Why does it appear on the webpack dev server?

3. If I use the component under views/ for the second time, the screen does not appear. Why does the screen appear when I use the component in the top vue/components?

I wanted to dig into the bundling process of Webpeck, but I couldn't understand it well because the code was vast and my knowledge was lacking. I'd appreciate it if you could recommend an article that might be helpful.

Thanks to those who reply in advance.

example.

https://github.com/Dailyscat/admin_vue_test

My directory architecture:

resource

[enter image description here][1]

vue
       
[enter image description here][2]

  [1]: https://i.stack.imgur.com/Rsace.png
  [2]: https://i.stack.imgur.com/CazF8.png

my vue.config.js

        // https://cli.vuejs.org/config
    const ExtractTextPlugin = require('mini-css-extract-plugin')
    // const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin
    let webpack = require('webpack')
    const pages = {
      sample: 'src/views/sample/main.js',
      modelProduct: 'src/views/modelProduct/main.js',
      productCategory: 'src/views/productCategory/main.js',
      productCategoryKpi: 'src/views/productCategory/kpi/main.js',
      productCategoryDetail: 'src/views/productCategory/detail/main.js',
      productCategoryMapping: 'src/views/productCategoryMapping/main.js',
      searchEvaluation: 'src/views/searchEvaluation/main.js',
      modal: 'src/views/modal/main.js',
      merchantFeedInfo: 'src/views/merchants/feedInfo/main.js',
      topCycle: 'src/views/topCycle/main.js',
      products: 'src/views/products/main.js',
      prohibitionKeyword: 'src/views/keyword/prohibition/main.js',
      coordinates: 'src/views/coordinates/main.js',
      productChangeHistory: 'src/views/productChangeHistory/main.js',
      merchantManagement: 'src/views/merchants/management/main.js',
      cmpManagement: 'src/views/keyword/cmpManagement/main.js',
      categoryAffiliate: 'src/views/category/affiliate/main.js',
      categoryManagement: 'src/views/category/management/main.js',
      categoryStandardSearch: 'src/views/category/standardSearch/main.js',
      catalogChangeHistory: 'src/views/catalogChangeHistory/main.js',
      allowedProduct: 'src/views/keyword/allowedProduct/main.js',
    	zProductDetail: 'src/views/products/details/main.js'
    }
    
    module.exports = {
      filenameHashing: false,
      outputDir: '../resources/static',
      devServer: {
        disableHostCheck: true,
        historyApiFallback: true,
        proxy: {
          '/admin': {
            target: 'http://localhost:8091'
          }
        },
        port: 18091
      },
      pages,
      configureWebpack: {
        plugins: [
          // new BundleAnalyzerPlugin(),
          new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)
        ],
        optimization: {
          chunkIds: 'named',
          splitChunks: {
            cacheGroups: {
              vendors: {
                name: 'chunk-vendors',
                test: /[\\/]node_modules[\\/]/,
                chunks: 'all'
              },
              vendor: {
                test: /[\\/]node_modules[\\/](xlsx)[\\/]/,
                chunks: 'initial',
                name: 'chunk-xlsx',
                priority: 10,
                enforce: true
              }
            }
          }
        },
        output: {
          filename: 'js/[name].js'
        }
      },
    
      chainWebpack: config => {
        Object.keys(pages).forEach(page => {
          config.module
            .rule('vue')
            .use('vue-loader')
            .loader('vue-loader')
            .tap(options => {
              // modify the options...
              return options
            })
          config.plugins.delete(`html-${page}`)
          config.plugins.delete(`preload-${page}`)
          config.plugins.delete(`prefetch-${page}`)
        })
    
        config.plugin('extract-css').use(ExtractTextPlugin, [
          {
            filename: 'css/[name].css',
            allChunks: true
          }
        ])
      }
    }

**Comment by edmorley** [comment]
Hi! This repo is for a library that makes it easier to manage webpack configurations, which doesn't seem related to the question. For Vue support, please ask the Vue project, and for webpack support, please ask the webpack project. Many thanks!
