### ISSUE TITLE
Why tap functions return undefined?

### ISSUE THREAD

**Issue by hulahulahhh** [neutrinojs/webpack-chain#321]
Error:   `TypeError: Cannot read property 'fallback' of undefined`

code: 
```
   option.module
      .rule('fonts')
      .use('url-loader')
      .loader('url-loader')
      .tap(options => {
        console.log(options)
        options.fallback.options.name = 'static/font/[name].[hash:8].[ext]'
        return options
      })
```
And when i log the `options` that the `tap` returned, the log showed `undefined`

Version: 
```
@vue/cli-service@^5.0.0-beta.7
webpack-chain@^6.5.1
```

**Comment by edmorley** [comment]
Hi! In your example,`options` has not yet been set previously, so there is no existing value. `.tap()` is for modifying an existing value, if there is none, you need to handle the case where it needs to be set for the first time.
