### ISSUE TITLE
config.output.chunkLoadingGlobal is not a function

### ISSUE THREAD

**Issue by huixisheng** [neutrinojs/webpack-chain#331]
```
output.jsonpFunction renamed to output.chunkLoadingGlobal
output.chunkCallbackFunction renamed to output.chunkLoadingGlobal
```
https://webpack.js.org/blog/2020-10-10-webpack-5-release/#changes-to-the-structure

**Comment by edmorley** [comment]
Closing since unfortunately this project is no longer maintained:
https://github.com/neutrinojs/webpack-chain/issues/358
