### ISSUE TITLE
How do I write this configuration ? 

### ISSUE THREAD

**Issue by Deja-vuuu** [neutrinojs/webpack-chain#332]
```
module: {
    rules: [
      {
        test: /\.mjs$/,
        include: /node_modules/,
        type: 'javascript/auto'
      }
    ]
  }
```

<img width="956" alt="image" src="https://user-images.githubusercontent.com/27748682/166112253-04165833-8300-413d-b1b4-93141f1de438.png">

**Comment by Deja-vuuu** [comment]
<img width="956" alt="image" src="https://user-images.githubusercontent.com/27748682/166112245-a5559946-e011-4235-87d6-9c400dadce01.png">

**Comment by Deja-vuuu** [comment]
config.module
      .rule('mjs$')
      .test(/\.mjs$/)
      .include.add(/node_modules/)
      .end()
      .type('javascript/auto');
  },

**Comment by edmorley** [comment]
Closing since unfortunately this project is no longer maintained:
https://github.com/neutrinojs/webpack-chain/issues/358
