### ISSUE TITLE
sideEffetcs method ts declare

### ISSUE THREAD

**Issue by javaxiu** [neutrinojs/webpack-chain#333]
As this issue https://github.com/neutrinojs/webpack-chain/issues/45 metioned about,  `config.module.rule().sideEffects` should be available.
And this method does available in webpack-chain@6.5.1 already, but does not exist on type declare

![image](https://user-images.githubusercontent.com/4281225/167251747-91d348b1-475b-47ca-9afa-c10897bee186.png)

**Comment by edmorley** [comment]
Closing since unfortunately this project is no longer maintained:
https://github.com/neutrinojs/webpack-chain/issues/358
