### ISSUE TITLE
This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

### ISSUE THREAD

**Issue by harrytothemoon** [neutrinojs/webpack-chain#334]
Due to the project requirements, I have to set `allowSyntheticDefaultImports` parameter to `false` in `tsconfig.json`, but here I will report an error regardless of whether I use the method of 
`import * as WebpackChain from 'webpack-chain'`, 
`import WebpackChain from 'webpack-chain'` or 
`import WebpackChain =require('webpack-chain')`.

I wonder if there are other solutions?

https://github.com/neutrinojs/webpack-chain/blob/da73fab944e5ba6e1e902a7e134709907c8bea50/types/index.d.ts#L5

**Comment by edmorley** [comment]
Closing since unfortunately this project is no longer maintained:
https://github.com/neutrinojs/webpack-chain/issues/358
