### ISSUE TITLE
Externals config for specific entry

### ISSUE THREAD

**Issue by Amanda111** [neutrinojs/webpack-chain#339]
In webpack, externals can be added to entry config. [https://github.com/webpack/webpack/issues/731](https://github.com/webpack/webpack/issues/731#issuecomment-71707269)
```
[
  {
    entry: { app: ['./src/app/index'] }
  },
  {
    entry: { app: ['./src/app/index'] },
    externals: { jquery: "var jQuery" }
  }
]
```

How can I config entry using webpack-chain ? Is the following possible in webpack-chain?
```
    config
      .entry('web-bundle')
      .add('./src/view.js')
      .externals([
        {
           jquery: "var jQuery"
        }
      ]
      .end();
```

**Comment by edmorley** [comment]
Closing since unfortunately this project is no longer maintained:
https://github.com/neutrinojs/webpack-chain/issues/358
