### ISSUE TITLE
support asset modules with generator

### ISSUE THREAD

**Issue by xurna** [neutrinojs/webpack-chain#344]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `webpack-chain@6.5.1` for the project I'm working on.

When I use webapck 5 , to add a module rule width generator,
not use webapck chain,the code like this:
`rules: [
	{ 
		test: /\.png/, 
		type: 'asset', 
		generator: { 
	      	filename: 'img/[name].[hash:8][ext]'
	 	} 
	}
]` 
to use weback chain, the code is 
`config.module
        .rule('images')
        .type('asset')
        .generator({
          filename: 'img/[name].[hash:8][ext]',
        })
        .parser({
          dataUrlCondition: {
            maxSize: 5 * 1024
        })`
but it accur error:
 TypeError: config.module.rule(...).test(...).type(...).generator is not a function

I found that the lastest webpack-chain is not support `generator`, so 
Here is the diff that solved my problem:

```diff
diff --git a/node_modules/webpack-chain/src/Rule.js b/node_modules/webpack-chain/src/Rule.js
index f300699..ef383b5 100644
--- a/node_modules/webpack-chain/src/Rule.js
+++ b/node_modules/webpack-chain/src/Rule.js
@@ -39,6 +39,7 @@ const Rule = Orderable(
         'sideEffects',
         'test',
         'type',
+        'generator',
       ]);
     }
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by s-wada-np** [comment]
Do it like this.

```js
{
  chainWebpack: (config) => {
    config.module
      .rule('svg')
      .test(/\.svg$/)
      .type('asset/inline')
      .set(
        'generator',
        { dataUrl: (content) => svgToMiniDataURI(content.toString()) },
      );
  },
}
```

**Comment by edmorley** [comment]
Closing since unfortunately this project is no longer maintained:
https://github.com/neutrinojs/webpack-chain/issues/358
