### ISSUE TITLE
How to add a plugin developed based on unplugin ?

### ISSUE THREAD

**Issue by hardmanhong** [neutrinojs/webpack-chain#352]
```js
const { sentryWebpackPlugin } = require('@sentry/webpack-plugin');
config.plugin('sentry-webpack').use(sentryWebpackPlugin,options)
```
The above code will prompt is not a constructor

**Comment by hardmanhong** [comment]
> ```js
> const { sentryWebpackPlugin } = require('@sentry/webpack-plugin');
> config.plugin('sentry-webpack').use(sentryWebpackPlugin,options)
> ```
> 
> The above code will prompt is not a constructor

Resolve.
```js
config
      .plugin('sentry-webpack')
      .use(sentryWebpackPlugin, [options]
      .init((Plugin,args)=> Plugin(...args))
```

**Comment by edmorley** [comment]
Closing since unfortunately this project is no longer maintained:
https://github.com/neutrinojs/webpack-chain/issues/358
