### ISSUE TITLE
Does  webpack-chain support webpack5 resolve.fallback?

### ISSUE THREAD

**Issue by ljmCoder** [neutrinojs/webpack-chain#356]
Does  webpack-chain support webpack5 resolve.fallback?

![image](https://github.com/neutrinojs/webpack-chain/assets/41459781/306c75a7-591e-4298-9cc0-9cd1a3fd6648)

**Comment by edmorley** [comment]
Closing since this project is no longer maintained:
https://github.com/neutrinojs/webpack-chain/issues/358
