### ISSUE TITLE
How to configure multiple pages?

### ISSUE THREAD

**Issue by jujubone** [neutrinojs/webpack-chain#47]
`config
  .entry('index')
    .add({
    pageOne: './src/pageOne/index.js',
    pageTwo: './src/pageTwo/index.js',
    pageThree: './src/pageThree/index.js'
  })
    .end()`
This is error

**Comment by edmorley** [comment]
Hi!

Multiple entrypoints and/or multi-main entries are defined like so:

```js
config
  .entry('index')
    .add('src/index.js')
    .end()
  .entry('a-second-page')
    .add('src/foo.js')
    .add('src/bar.js')
    .end();
  .entry('a-third-page')
    .add('src/baz.js');
```

If there's a way to make this clearer in the docs we'd more than gratefully accept a PR if you had a spare moment? :-)

**Comment by wss610** [comment]
@edmorley Thank you very much for your answer.
My English is not very good, so there is nothing I can do to enhance the docs.
I'm sorry.

**Comment by zen-li** [comment]
Hi @edmorley 
I am wondering how to configure multi-main entries with different html template, could you guide me?

Very thankful.

**Comment by eliperelman** [comment]
@zen-li In Neutrino we do the following:

https://github.com/mozilla-neutrino/neutrino-dev/blob/5b78b4134489a667e72d366c7b4b3a3f357315e0/packages/web/index.js#L119-L134

The process here is to create an entry and an instance of html-webpack-plugin/template for every main entry you have.

```js
['index', 'admin'].forEach(page => {
  config.entry(page).add(`src/${page}`);

  config.plugin(`html-${page}`).use(HtmlWebpackPlugin, [{
    filename: `${page}.html`
  }]);
});
```

**Comment by zen-li** [comment]
Thanks @eliperelman , that was very helpful.

**Comment by eliperelman** [comment]
Actually, keeping open for docs.

**Comment by up9cloud** [comment]
For those wanna replace whole entry, can do:

```js
const page = 'login'
config.entryPoints.clear()
config.entry(page).add(`src/${page}`)
```

**Comment by yordis** [comment]
@eliperelman what kind of documentation would you like to write?
