### ISSUE TITLE
Add  type definition file

### ISSUE THREAD

**Issue by cecilphillip** [neutrinojs/webpack-chain#62]
I'm using this with Visual Studio Code and it would be great to explore the available API operations via the autocomplete of the editor. If there's a .d.ts file in the npm package, most editors should be able to enable this.

**Comment by edmorley** [comment]
Hi! If someone was up for adding type definitions to the webpack-chain repository (along with validation of them in CI and an easy way to verify when developing locally), then we'd be happy to accept them :-)

**Comment by edmorley** [comment]
Released in webpack-chain v5.2.0:
https://www.npmjs.com/package/webpack-chain/v/5.2.0
