### ISSUE TITLE
Add "serve" method to Config to support "webpack-serve"

### ISSUE THREAD

**Issue by ElMassimo** [neutrinojs/webpack-chain#65]
[__webpack-serve__](https://github.com/webpack-contrib/webpack-serve) is a `webpack-dev-server` alternative that targets modern browsers.

The configuration is slightly different, as it delegates most options to [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware#options) and [`webpack-hot-client`](https://github.com/webpack-contrib/webpack-hot-client#options) through the `dev` and `hot` options respectively.

It expects options to be provided through the `serve` key in the Webpack config, but right now `webpack-chain` does not let that option go through, which would be convenient even if you decide not to create shorthands for the different parts of it.

**Comment by eliperelman** [comment]
@ElMassimo do you happen to know if all the options going through the `serve` option are the same as what `devServer` accepts?

**Comment by ElMassimo** [comment]
Unfortunately they are slightly different, but `dev` does use [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware#options), so they have that in common:
```js
const { logLevel, host, port, notifyOnErrors } = devServerConfig

const webpackServeConfig = {
  dev: {
    logLevel,
    publicPath: webpackConfig.output.get('publicPath'),
  },
  hot: {
    allEntries: true, // Else only the first entry would get the HMR client script.
    logLevel: 'warn',
  },
  ...devServerConfig
}
```

**Comment by eliperelman** [comment]
It also looks like webpack-serve is going to be either deprecated, not maintained, or rolled into webpack-cli, so I'm going to close this out. Please re-open if this isn't acceptable. Thanks!
