### ISSUE TITLE
Document merge function import

### ISSUE THREAD

**Issue by IlyaSemenov** [neutrinojs/webpack-chain#67]
Here https://github.com/mozilla-neutrino/webpack-chain#config-module-rules-uses-loaders-modifying-options the example says:

```js
config.module
  .rule('compile')
    .use('babel')
      .tap(options => merge(options, { plugins: ['babel-plugin-syntax-object-rest-spread'] }));
```

However it's not mentioned anywhere where `merge` is supposed to come from. I believe that should be documented at least once.

**Comment by ducky-hong** [comment]
I hope this should be documented. I imported `merge` like `const merge = require('deepmerge')`.

**Comment by edmorley** [comment]
@eliperelman is this example referring to deepmerge's `merge()` or that from [babel-merge](https://github.com/eliperelman/babel-merge)? I'm presuming the latter?

**Comment by luckydonald** [comment]
I had success with [`webpack-merge`](https://github.com/survivejs/webpack-merge):
```js
var merge = require('webpack-merge');
```
