### ISSUE TITLE
Transform webpack configuration to webpack-chain

### ISSUE THREAD

**Issue by SLMNBJ** [neutrinojs/webpack-chain#90]
How can i transform an existing webpack configuration object to webpack-chain format?
There is some tools that can do it ?

**Comment by eliperelman** [comment]
You can use the `merge` method, but the identifiers won't be perfect, and as far as I know there aren't any tools that would do this for you.

```js
config.merge({ ...webpackConfig })
```

**Comment by lzane** [comment]
+1 Need this function too.
